server:
  port: 5678

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  out:
    path: /home/tim/images/output/
  path: /home/tim/images/
  media: https://www.adstech-x.com/media/

hashmap:
  maxSize: 1000
